### ISSUE TITLE
Leveling up

### ISSUE THREAD

**Issue by ConJamAnt** [ConJamAnt/Progaming-task-thingy#3]
More exp need for each level up

SOME KIND OF REWARD!!!

**Comment by ConJamAnt** [comment]
Parts of a story for each reward
need to finish all tasks for whole story

**Comment by EthanRayner** [comment]
Use a combo box to determine difficulty so that the appropriate amount of exp can be given to the player.

Code a levelling up system in which each level costs more experience than the last.

**Comment by ConJamAnt** [comment]
each level up requires 10 more than last
story part unlocked every 2 level ups
